### Embedding Layer Implementation

In [49]:
#importing libraries

import tensorflow
from tensorflow.keras.preprocessing.text import one_hot #this is deprecated 
from tensorflow.keras.layers import TextVectorization

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [50]:
#sample sentences

sentences = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am a good girl',
        'i am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [51]:
voc_size=10000
one_hot_representation = [one_hot(sent, voc_size) for sent in sentences]
one_hot_representation

[[1240, 2186, 9144, 2492],
 [1240, 2186, 9144, 1944],
 [1240, 5439, 9144, 315],
 [5129, 2365, 8524, 4352, 7451],
 [5129, 2365, 8524, 4352, 4760],
 [5315, 1240, 738, 9144, 961],
 [6600, 7220, 7616, 4352]]

In [52]:
from tensorflow.keras.layers import TextVectorization

'''tf.keras.layers.TextVectorization(
    max_tokens=None,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=None,
    output_mode='int',
    output_sequence_length=None,
    pad_to_max_tokens=False,
    vocabulary=None,
    idf_weights=None,
    sparse=False,
    ragged=False,
    encoding='utf-8',
    name=None)'''

vectorize_layer = TextVectorization(max_tokens=voc_size, output_mode="int")
vectorize_layer.adapt(sentences)

In [53]:
sent_vectors=vectorize_layer(sentences)

In [54]:
#ragged vectors

vectorize_layer = TextVectorization(max_tokens=voc_size, ragged=True)

vectorize_layer.adapt(sentences)

input_sentences = vectorize_layer(sentences)
input_sentences


<tf.RaggedTensor [[2, 6, 3, 14], [2, 6, 3, 16], [2, 19, 3, 13], [5, 7, 8, 4, 17],
 [5, 7, 8, 4, 18], [12, 2, 15, 3, 10], [9, 11, 20, 4]]>

In [61]:
# passing ragged vector through pad_sequences

sequences = [sen.numpy() for sen in input_sentences]
padded_sequences=pad_sequences(sequences, maxlen=5)
padded_sequences

array([[ 0,  2,  6,  3, 14],
       [ 0,  2,  6,  3, 16],
       [ 0,  2, 19,  3, 13],
       [ 5,  7,  8,  4, 17],
       [ 5,  7,  8,  4, 18],
       [12,  2, 15,  3, 10],
       [ 0,  9, 11, 20,  4]], dtype=int32)

In [64]:
#word embedding representation

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10, input_length=5))

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [57]:
model.compile(loss="mse", optimizer="adam")

In [65]:
model(sent_vectors)

<tf.Tensor: shape=(7, 5, 10), dtype=float32, numpy=
array([[[ 4.79474328e-02,  7.59837776e-03,  1.32156536e-03,
          4.21479456e-02,  3.89842279e-02, -3.23591381e-03,
          4.01349328e-02, -1.75191052e-02,  3.89192812e-02,
         -4.86804843e-02],
        [-9.74524021e-03,  1.09129064e-02,  3.87036689e-02,
         -2.71185879e-02,  3.28460447e-02,  1.41898282e-02,
          4.73553576e-02,  2.97324322e-02, -3.03587448e-02,
         -4.95963804e-02],
        [-7.98679516e-03, -1.03657022e-02, -3.45030427e-02,
         -4.22792435e-02, -1.93528067e-02, -3.04147955e-02,
         -4.95016836e-02, -2.89862882e-02, -3.71944159e-04,
         -6.09741360e-03],
        [ 8.94521549e-03,  2.84684561e-02, -1.08883157e-02,
          3.57317813e-02, -4.01129723e-02, -4.63289507e-02,
          1.04109161e-02,  2.21618265e-03, -4.85790744e-02,
          4.01959568e-03],
        [ 3.02226581e-02,  1.70675032e-02,  3.35005037e-02,
          3.18449736e-03, -5.78169897e-03,  2.75364630e-02,
